/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#a0efff",
        "surface-container-lowest": "#0d0e11",
        "on-background": "#e3e2e5",
        "surface-container": "#1e2022",
        "on-primary-container": "#00616e",
        surface: "#121316",
        "on-primary": "#00363e",
        "surface-container-highest": "#343538",
        "inverse-surface": "#e3e2e5",
        "primary-fixed-dim": "#00daf5",
        "on-tertiary-container": "#4f5964",
        "surface-dim": "#121316",
        "surface-container-low": "#1a1c1e",
        "tertiary-fixed": "#d9e3f1",
        background: "#121316",
        "on-tertiary-fixed-variant": "#3e4852",
        "secondary-fixed-dim": "#ffb4a3",
        "secondary-container": "#b22301",
        "on-secondary-fixed": "#3d0600",
        "tertiary-fixed-dim": "#bdc7d4",
        "surface-tint": "#00daf5",
        "surface-variant": "#343538",
        "on-tertiary-fixed": "#131c26",
        outline: "#859397",
        "tertiary-container": "#c6d0dd",
        "surface-container-high": "#292a2d",
        "on-primary-fixed-variant": "#004e59",
        "on-error-container": "#ffdad6",
        "primary-container": "#19e3ff",
        "surface-bright": "#38393c",
        "outline-variant": "#3b494c",
        "on-secondary-fixed-variant": "#8c1900",
        "inverse-primary": "#006876",
        error: "#ffb4ab",
        "secondary-fixed": "#ffdad2",
        "on-surface-variant": "#bac9cd",
        "on-secondary-container": "#ffc8bc",
        "on-surface": "#e3e2e5",
        secondary: "#ffb4a3",
        primary: "#c1f4ff",
        "on-primary-fixed": "#001f25",
        "inverse-on-surface": "#2f3033",
        tertiary: "#e2ecf9",
        "error-container": "#93000a",
        "on-secondary": "#630f00",
        "on-error": "#690005",
        "on-tertiary": "#28313b",
      },
      spacing: {
        "space-md": "1rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
      },
      keyframes: {
        "arc-spin": {
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "arc-spin-40": "arc-spin 40s linear infinite",
        "arc-spin-32": "arc-spin 32s linear infinite",
        "arc-spin-24-rev": "arc-spin 24s linear infinite reverse",
        "arc-spin-18-rev": "arc-spin 18s linear infinite reverse",
        "arc-spin-18": "arc-spin 18s linear infinite",
        "arc-spin-12": "arc-spin 12s linear infinite",
        "arc-spin-10": "arc-spin 10s linear infinite",
        "arc-spin-8": "arc-spin 8s linear infinite",
      },
    },
  },
  plugins: [],
};
